services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-api
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tashkent
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
