# Development image
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# Dev dependencies ham o‘rnatiladi
RUN npm install

COPY . .

EXPOSE 3000

# Nest CLI dan foydalanish uchun dev mode
CMD ["npm", "run", "start:dev"]
